name: Test

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  flutter:
    name: Run Flutter tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Install dependencies
        working-directory: app/resident_tracker
        run: flutter pub get

      - name: Run tests
        working-directory: app/resident_tracker
        run: flutter test
